// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Vec2$ReMatrix = require("./Vec2.bs.js");

var a = /* tuple */[
  1.0,
  2.0
];

var b = /* tuple */[
  2.0,
  3.0
];

var c = Vec2$ReMatrix.add(a, b);

exports.a = a;
exports.b = b;
exports.c = c;
/* c Not a pure module */
