// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function acosh(x) {
  return Math.log(x + Math.sqrt(x * x + 1.0));
}

function asinh(x) {
  return Math.log(x + Math.sqrt(x * x - 1.0));
}

function atanh(x) {
  return Math.log((1.0 + x) / (1.0 - x)) * 0.5;
}

function clamp(a, b, c) {
  return Caml_obj.caml_max(a, Caml_obj.caml_min(b, c));
}

function deg2rad(a) {
  return a * 3.1415926535 / 180.0;
}

function rad2deg(a) {
  return a * 180.0 / 3.1415926535;
}

var pi = 3.1415926535;

exports.acosh = acosh;
exports.asinh = asinh;
exports.atanh = atanh;
exports.pi = pi;
exports.clamp = clamp;
exports.deg2rad = deg2rad;
exports.rad2deg = rad2deg;
/* No side effect */
